BOT_TOKEN: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
INTERVIEW_TIME: "10:30 11:00 11:30 11:50 15:30 16:00 16:30 17:00"
ADDRESS: "г. Казань, ул. Спартаковская д. 23, приемная 4-го этажа, при выходе из лифта"
DB_PATH: /home/user/super_important.db
INITIAL_ADMIN_USERNAME: onetimeusername
INITIAL_ADMIN_PHONE: "+78005553535"
INITIAL_ADMIN_NAME: "Ну типо разраб"
